### ISSUE TITLE
Add tests and examples

### ISSUE THREAD

**Issue by tonyskapunk** [tonyskapunk/yctf#1]
- [ ] Tests
- [ ] Examples/Doc

**Comment by komish** [comment]
I'd like to help add some tests here. Any specific tests you had in mind?

**Comment by tonyskapunk** [comment]
Hi @komish, thanks for the interest in this project!

Ideally, I'd like to have full test coverage :smile_cat:. For starters, I think each handler should have a test or tests, as well as the models.

I know there are a handful of handers, feel free to start with one at a time, and see how it goes, does that sound reasonable to you?

**Comment by komish** [comment]
OK, this will take some time. I will return with questions as they come up.
Thanks!
